#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Version generation script (Deno version)
 *
 * Reads package.json and generates cli/version.ts with the version information.
 * This ensures the version is available for both development and bundled builds.
 */

try {
  // Read version from package.json
  const packageJsonText = await Deno.readTextFile("package.json");
  const packageJson = JSON.parse(packageJsonText);
  const version = packageJson.version;

  // Generate version.ts content
  const versionFileContent = `// Auto-generated file - do not edit manually
// This file is generated by scripts/generate-version.ts
export const VERSION = "${version}";
`;

  // Write version.ts file
  await Deno.writeTextFile("cli/version.ts", versionFileContent);

  console.log(`✅ Generated cli/version.ts with version: ${version}`);
} catch (error) {
  console.error("❌ Failed to generate version.ts:", error.message);
  Deno.exit(1);
}