// Copyright 2026 The OPA Authors.  All rights reserved.
// Use of this source code is governed by an Apache2
// license that can be found in the LICENSE file.

package rego

import (
	"slices"
	"strconv"

	"github.com/open-policy-agent/opa/v1/ast"
)

var templateStringRef = ast.InternalTemplateString.Ref()

// reconstructTemplateStrings rewrites the internal.template_string calls that
// template strings are compiled into back into template-string terms, so that
// partial evaluation output reads (and compiles) as ordinary Rego. Calls that
// can't be expressed as template strings without changing semantics are left
// as they are. Queries and modules are copied before they are modified.
func reconstructTemplateStrings(c *ast.Compiler, queries []ast.Body, support []*ast.Module) ([]ast.Body, []*ast.Module) {
	var arity func(ast.Ref) int

	for i := range queries {
		if !containsTemplateStringCall(queries[i]) {
			continue
		}
		if arity == nil {
			arity = partialArity(c, support)
		}
		query := queries[i].Copy()
		queries[i] = newTemplateStringRewriter(query, arity).rewriteBody(query, ast.ReservedVars)
	}

	for i := range support {
		if !containsTemplateStringCall(support[i]) {
			continue
		}
		if arity == nil {
			arity = partialArity(c, support)
		}
		mod := support[i].Copy()
		for _, rule := range mod.Rules {
			for r := rule; r != nil; r = r.Else {
				scope := ast.ReservedVars.Copy()
				scope.Update(r.Head.Args.Vars())
				r.Body = newTemplateStringRewriter(r, arity).rewriteBody(r.Body, scope)
			}
		}
		support[i] = mod
	}

	return queries, support
}

// partialArity returns the arity of functions known to the compiler, or
// defined in the support modules generated by partial evaluation.
func partialArity(c *ast.Compiler, support []*ast.Module) func(ast.Ref) int {
	funcs := map[string]int{}
	for _, mod := range support {
		for _, rule := range mod.Rules {
			if len(rule.Head.Args) > 0 {
				funcs[mod.Package.Path.String()+"."+rule.Head.Ref().String()] = len(rule.Head.Args)
			}
		}
	}
	return func(ref ast.Ref) int {
		if n, ok := funcs[ref.String()]; ok {
			return n
		}
		return c.GetArity(ref)
	}
}

func containsTemplateStringCall(x any) bool {
	var found bool
	ast.WalkRefs(x, func(ref ast.Ref) bool {
		found = found || ref.Equal(templateStringRef)
		return found
	})
	return found
}

func isTemplateStringOperator(t *ast.Term) bool {
	ref, ok := t.Value.(ast.Ref)
	return ok && ref.Equal(templateStringRef)
}

// templateStringRewriter rewrites the bodies of a single query or rule.
type templateStringRewriter struct {
	arity func(ast.Ref) int
	// counts holds the number of occurrences of each var in the query or rule,
	// used to decide whether generated bindings have any other use.
	counts map[ast.Var]int
	next   int
}

func newTemplateStringRewriter(root any, arity func(ast.Ref) int) *templateStringRewriter {
	tsr := &templateStringRewriter{arity: arity, counts: map[ast.Var]int{}}
	ast.WalkVars(root, func(v ast.Var) bool {
		tsr.counts[v]++
		return false
	})
	return tsr
}

// wildcard returns a wildcard var that doesn't clash with any var in the query or rule.
func (tsr *templateStringRewriter) wildcard() *ast.Term {
	for {
		v := ast.Var(ast.WildcardPrefix + "ts" + strconv.Itoa(tsr.next))
		tsr.next++
		if _, ok := tsr.counts[v]; !ok {
			tsr.counts[v] = 1
			return ast.NewTerm(v)
		}
	}
}

// rewriteBody reconstructs the template strings in body, and in any closure
// nested in it. outer holds the vars bound outside of body.
func (tsr *templateStringRewriter) rewriteBody(body ast.Body, outer ast.VarSet) ast.Body {
	if !containsTemplateStringCall(body) {
		return body
	}

	scope := outer.Copy()
	scope.Update(nonClosureVars(body))

	for _, expr := range body {
		tsr.rewriteClosures(expr, scope)
	}

	removed := make([]bool, len(body))
	guards := make([][]*ast.Expr, len(body))
	var inlinable []*ast.Expr

	for i, expr := range body {
		if terms, ok := expr.Terms.([]*ast.Term); ok && isTemplateStringOperator(terms[0]) && (len(terms) == 2 || len(terms) == 3) {
			ts, gs, elide, ok := tsr.templateString(terms[1], body, expr.With, scope)
			if !ok || (len(gs) > 0 && expr.Negated) {
				continue
			}

			var repl *ast.Expr
			if len(terms) == 3 {
				repl = ast.Equality.Expr(terms[2], ts)
				if v, ok := terms[2].Value.(ast.Var); ok && v.IsGenerated() && tsr.counts[v] == 2 {
					inlinable = append(inlinable, repl)
				}
			} else {
				repl = ast.NewExpr(ts)
			}
			repl.Negated = expr.Negated
			repl.With = expr.With
			repl.Location = expr.Location

			body[i] = repl
			guards[i] = gs
			for _, j := range elide {
				removed[j] = true
			}
			continue
		}

		// Calls nested in other expressions, e.g. `x = internal.template_string([...])`.
		ast.NewGenericVisitor(func(x any) bool {
			switch x := x.(type) {
			case *ast.ArrayComprehension, *ast.SetComprehension, *ast.ObjectComprehension, *ast.Every:
				return true
			case *ast.Term:
				call, ok := x.Value.(ast.Call)
				if !ok || len(call) != 2 || !isTemplateStringOperator(call[0]) {
					return false
				}
				ts, gs, elide, ok := tsr.templateString(call[1], body, expr.With, scope)
				if !ok || (len(gs) > 0 && expr.Negated) {
					return true
				}
				x.Value = ts.Value
				guards[i] = append(guards[i], gs...)
				for _, j := range elide {
					removed[j] = true
				}
				return true
			}
			return false
		}).Walk(expr)
	}

	exprs := make([]*ast.Expr, 0, len(body))
	for i, expr := range body {
		if !removed[i] {
			exprs = append(exprs, guards[i]...)
			exprs = append(exprs, expr)
		}
	}

	return ast.NewBody(inlineTemplateStringBindings(exprs, inlinable)...)
}

// inlineTemplateStringBindings folds `g = $"..."`, where the generated var g
// has exactly one other use, into the unification that uses g, e.g.
// `g = $"{x}"; g = "1"` becomes `$"{x}" = "1"`.
func inlineTemplateStringBindings(exprs []*ast.Expr, inlinable []*ast.Expr) []*ast.Expr {
	for _, binding := range inlinable {
		g := binding.Operand(0)
		var use *ast.Expr
		var operand int
		for _, expr := range exprs {
			if expr == binding || expr.Negated || !expr.IsEquality() || !withEqual(expr.With, binding.With) {
				continue
			}
			for k := range 2 {
				if expr.Operand(k).Equal(g) {
					use, operand = expr, k
				}
			}
		}
		if use == nil {
			continue
		}
		use.Terms.([]*ast.Term)[operand+1] = binding.Operand(1)
		exprs = slices.DeleteFunc(exprs, func(e *ast.Expr) bool { return e == binding })
	}
	return exprs
}

func (tsr *templateStringRewriter) rewriteClosures(x any, scope ast.VarSet) {
	ast.NewGenericVisitor(func(x any) bool {
		switch x := x.(type) {
		case *ast.ArrayComprehension:
			x.Body = tsr.rewriteBody(x.Body, scope)
			return true
		case *ast.SetComprehension:
			x.Body = tsr.rewriteBody(x.Body, scope)
			return true
		case *ast.ObjectComprehension:
			x.Body = tsr.rewriteBody(x.Body, scope)
			return true
		case *ast.Every:
			tsr.rewriteClosures(x.Domain, scope)
			s := scope.Copy()
			s.Update(x.KeyValueVars())
			x.Body = tsr.rewriteBody(x.Body, s)
			return true
		}
		return false
	}).Walk(x)
}

// templateString converts the array argument of an internal.template_string
// call in body into a template string. It also returns the expressions that
// must precede the template string to preserve the semantics of the call, and
// the indices of the generated bindings in body that become redundant.
func (tsr *templateStringRewriter) templateString(arg *ast.Term, body ast.Body, with []*ast.With, scope ast.VarSet) (*ast.Term, []*ast.Expr, []int, bool) {
	arr, ok := arg.Value.(*ast.Array)
	if !ok {
		return nil, nil, nil, false
	}

	parts := make([]ast.Node, 0, arr.Len())
	var guards []*ast.Expr
	var elide []int

	for i := range arr.Len() {
		elem := arr.Elem(i)

		// Interpolated comprehensions are bound to generated vars by the compiler.
		if v, ok := elem.Value.(ast.Var); ok {
			j := bindingOf(v, body, with)
			if j < 0 {
				return nil, nil, nil, false
			}
			if tsr.counts[v] == 2 {
				elide = append(elide, j)
			}
			if body[j].Operand(0).Equal(elem) {
				elem = body[j].Operand(1)
			} else {
				elem = body[j].Operand(0)
			}
		}

		switch v := elem.Value.(type) {
		case ast.String:
			if len(v) > 0 {
				parts = append(parts, elem)
			}
		case ast.Number, ast.Boolean, ast.Null:
			parts = append(parts, elem)
		case *ast.SetComprehension:
			part, ok := tsr.comprehensionPart(v, scope)
			if !ok {
				return nil, nil, nil, false
			}
			parts = append(parts, part)
		case ast.Set:
			switch v.Len() {
			case 0:
				// What the built-in prints for an undefined value.
				parts = append(parts, ast.StringTerm("<undefined>"))
			case 1:
				x := v.Slice()[0]
				switch {
				case ast.IsScalar(x.Value):
					parts = append(parts, x)
				case ast.IsConstant(x.Value):
					parts = append(parts, templateStringExprPart(x, nil, x.Location))
				default:
					if _, ok := x.Value.(ast.Var); !ok {
						// The set is undefined when its element is, while an
						// interpolated expression would print "<undefined>", so
						// keep the requirement that the element is defined.
						guards = append(guards, guardExpr(tsr.wildcard(), x, with))
					}
					parts = append(parts, templateStringExprPart(x.Copy(), nil, x.Location))
				}
			default:
				return nil, nil, nil, false
			}
		default:
			return nil, nil, nil, false
		}
	}

	return ast.NewTerm(&ast.TemplateString{Parts: parts}).SetLocation(arg.Location), guards, elide, true
}

// bindingOf returns the index of the expression in body that binds v to a set
// or set comprehension, or -1 if there isn't exactly one such expression.
func bindingOf(v ast.Var, body ast.Body, with []*ast.With) int {
	found := -1
	for i, expr := range body {
		if expr.Negated || !expr.IsEquality() || !withEqual(expr.With, with) {
			continue
		}
		for k := range 2 {
			if expr.Operand(k).Value.Compare(v) != 0 {
				continue
			}
			switch expr.Operand(1 - k).Value.(type) {
			case ast.Set, *ast.SetComprehension:
				if found >= 0 {
					return -1
				}
				found = i
			}
		}
	}
	return found
}

func guardExpr(wildcard, x *ast.Term, with []*ast.With) *ast.Expr {
	guard := ast.Equality.Expr(wildcard, x.Copy())
	for _, w := range with {
		guard.With = append(guard.With, w.Copy())
	}
	return guard.SetLocation(x.Location)
}

func templateStringExprPart(x *ast.Term, with []*ast.With, loc *ast.Location) *ast.Expr {
	part := &ast.Expr{Terms: x, With: with, Location: loc}
	if call, ok := x.Value.(ast.Call); ok {
		part.Terms = []*ast.Term(call)
	}
	return part
}

// comprehensionPart converts a set comprehension produced by the compiler for
// an interpolated expression, e.g. `{x | y = input.y; count(y, z); x = z}`,
// back into that expression, e.g. `count(input.y)`. The comprehension body must
// consist only of bindings of vars local to the comprehension, and inlining
// them must leave an expression that only refers to vars bound outside of it.
func (tsr *templateStringRewriter) comprehensionPart(comp *ast.SetComprehension, scope ast.VarSet) (*ast.Expr, bool) {
	head, ok := comp.Term.Value.(ast.Var)
	if !ok {
		return nil, false
	}

	local := nonClosureVars(comp.Body)
	local.Add(head)
	local = local.Diff(scope)

	c := &comprehensionInliner{
		arity:    tsr.arity,
		body:     comp.Body,
		consumed: make([]bool, len(comp.Body)),
		local:    local,
	}

	root := c.definition(head, nil, true)
	if root < 0 {
		return nil, false
	}
	c.consumed[root] = true

	with := make([]*ast.With, len(comp.Body[root].With))
	for i, w := range comp.Body[root].With {
		value, ok := c.inline(w.Value, nil)
		if !ok {
			return nil, false
		}
		with[i] = w.Copy()
		with[i].Value = value
	}

	x, ok := c.inline(c.value(root, head), comp.Body[root].With)
	if !ok || slices.Contains(c.consumed, false) {
		return nil, false
	}

	part := templateStringExprPart(x.Copy(), with, comp.Body[root].Location)

	var escapes bool
	ast.WalkVars(part, func(v ast.Var) bool {
		escapes = escapes || local.Contains(v)
		return escapes
	})
	if escapes || nonClosureVars(part).DiffCount(scope) > 0 {
		return nil, false
	}

	return part, true
}

type comprehensionInliner struct {
	arity    func(ast.Ref) int
	body     ast.Body
	consumed []bool
	local    ast.VarSet
}

// definition returns the index of the only unconsumed expression that defines
// v, or -1. Unless anyWith is set, the expression must have the given with
// modifiers.
func (c *comprehensionInliner) definition(v ast.Var, with []*ast.With, anyWith bool) int {
	found := -1
	for i, expr := range c.body {
		if c.consumed[i] || expr.Negated || (!anyWith && !withEqual(expr.With, with)) {
			continue
		}
		if c.value(i, v) != nil {
			if found >= 0 {
				return -1
			}
			found = i
		}
	}
	return found
}

// value returns the term that the expression at index i binds v to, if any:
// the other side of a unification with v, or a call with v as its output.
func (c *comprehensionInliner) value(i int, v ast.Var) *ast.Term {
	expr := c.body[i]
	terms, ok := expr.Terms.([]*ast.Term)
	if !ok {
		return nil
	}

	if expr.IsEquality() {
		for k := range 2 {
			if x, other := expr.Operand(k), expr.Operand(1-k); x.Value.Compare(v) == 0 && !containsVar(other, v) {
				return other
			}
		}
		return nil
	}

	op, ok := terms[0].Value.(ast.Ref)
	if !ok || isTemplateStringOperator(terms[0]) {
		return nil
	}
	n := c.arity(op)
	if n < 0 || len(terms) != n+2 || terms[n+1].Value.Compare(v) != 0 {
		return nil
	}
	for _, arg := range terms[1 : n+1] {
		if containsVar(arg, v) {
			return nil
		}
	}
	return ast.CallTerm(slices.Clone(terms[:n+1])...)
}

// inline replaces the local vars in x, outside of closures, with the terms they
// are bound to by expressions with the given with modifiers.
func (c *comprehensionInliner) inline(x *ast.Term, with []*ast.With) (*ast.Term, bool) {
	switch v := x.Value.(type) {
	case ast.Var:
		if !c.local.Contains(v) {
			return x, true
		}
		i := c.definition(v, with, false)
		if i < 0 {
			return nil, false
		}
		c.consumed[i] = true
		return c.inline(c.value(i, v), with)
	case ast.Ref:
		ref := make(ast.Ref, 0, len(v))
		head, ok := c.inline(v[0], with)
		if !ok {
			return nil, false
		}
		switch h := head.Value.(type) {
		case ast.Ref:
			ref = append(ref, h...)
		case ast.Var:
			ref = append(ref, head)
		default:
			return nil, false
		}
		for _, t := range v[1:] {
			t, ok := c.inline(t, with)
			if !ok {
				return nil, false
			}
			ref = append(ref, t)
		}
		return ast.NewTerm(ref).SetLocation(x.Location), true
	case ast.Call:
		call := make(ast.Call, len(v))
		call[0] = v[0]
		for i := 1; i < len(v); i++ {
			t, ok := c.inline(v[i], with)
			if !ok {
				return nil, false
			}
			call[i] = t
		}
		return ast.NewTerm(call).SetLocation(x.Location), true
	case *ast.Array:
		terms := make([]*ast.Term, v.Len())
		for i := range v.Len() {
			t, ok := c.inline(v.Elem(i), with)
			if !ok {
				return nil, false
			}
			terms[i] = t
		}
		return ast.ArrayTerm(terms...).SetLocation(x.Location), true
	case ast.Set:
		terms := make([]*ast.Term, 0, v.Len())
		for _, elem := range v.Slice() {
			t, ok := c.inline(elem, with)
			if !ok {
				return nil, false
			}
			terms = append(terms, t)
		}
		return ast.SetTerm(terms...).SetLocation(x.Location), true
	case ast.Object:
		items := make([][2]*ast.Term, 0, v.Len())
		for _, key := range v.Keys() {
			k, ok := c.inline(key, with)
			if !ok {
				return nil, false
			}
			val, ok := c.inline(v.Get(key), with)
			if !ok {
				return nil, false
			}
			items = append(items, [2]*ast.Term{k, val})
		}
		return ast.ObjectTerm(items...).SetLocation(x.Location), true
	}
	// Scalars and closures (comprehensions and template strings): local vars in
	// closures can't be inlined without changing when they're evaluated.
	return x, true
}

func nonClosureVars(x any) ast.VarSet {
	vis := ast.NewVarVisitor().WithParams(ast.SafetyCheckVisitorParams)
	vis.Walk(x)
	vars := ast.NewVarSet()
	vars.Update(vis.Vars())
	return vars
}

func containsVar(x *ast.Term, v ast.Var) bool {
	var found bool
	ast.WalkVars(x, func(w ast.Var) bool {
		found = found || w == v
		return found
	})
	return found
}

func withEqual(a, b []*ast.With) bool {
	return slices.EqualFunc(a, b, (*ast.With).Equal)
}
